DROP TABLE IF EXISTS login_bonus_message_data;
CREATE TABLE IF NOT EXISTS `login_bonus_message_data` (`id` INTEGER NOT NULL,`login_bonus_id` INTEGER NOT NULL,`type` INTEGER NOT NULL,`day_count` INTEGER NOT NULL,`luck_pattern` INTEGER NOT NULL,`rate` INTEGER NOT NULL,`character_id` INTEGER NOT NULL,`character_name` TEXT NOT NULL,`message` TEXT NOT NULL,`voice_id` INTEGER NOT NULL,PRIMARY KEY(`id`));
INSERT INTO `login_bonus_message_data` VALUES (1,60000,1,0,0,1,190804,"カリン","新年を迎え、新たに始まる一日を\nおみくじで占ってみませんか？\n良い運勢であるほど、\n沢山のプレゼントが貰えますよ♪",1);
INSERT INTO `login_bonus_message_data` VALUES (2,60000,2,0,1,1,0,"","今日の運勢は姫吉！　あらゆる運気が最大を示しています！　　　今なら「伝説の吸血鬼」をも従え、世界征服も夢じゃありません！",0);
INSERT INTO `login_bonus_message_data` VALUES (3,60000,2,0,1,1,0,"","今日の運勢は姫吉！　やること全てが最高潮！　やばいですね☆　ラッキーアイテムはおにぎり！　お腹一杯で幸せが続くでしょう！",0);
INSERT INTO `login_bonus_message_data` VALUES (4,60000,2,0,1,2,0,"","今日の運勢は姫吉！　その高い運気はまさにショーグンの如く！　その溢れる威光は人々を惹きつけ、皆の人気者間違いなしです！",0);
INSERT INTO `login_bonus_message_data` VALUES (5,60000,2,0,2,1,0,"","今日の運勢は大吉！　運気がどんどん高まっています！　　　　　何をやっても、最大効率で素晴らしい結果になりますよ♪",0);
INSERT INTO `login_bonus_message_data` VALUES (6,60000,2,0,2,1,0,"","今日の運勢は大吉！　なにをやっても上手くいって大活躍！　　　そんな素敵なあなたを見て、後ろから誰かが……クスクス♪",0);
INSERT INTO `login_bonus_message_data` VALUES (7,60000,2,0,2,2,0,"","今日の運勢は大吉！　運気が高く、何かに挑戦すると良い結果に！隠れた才能が引き出されそう！　目指せヒデサ……ではなく秀才！",0);
INSERT INTO `login_bonus_message_data` VALUES (8,60000,2,0,3,1,0,"","今日の運勢は中吉！　商売運が上がってきています！　　　　　　ラッキーアイテムはたいやき！　和菓子パワーで売上アップです！",0);
INSERT INTO `login_bonus_message_data` VALUES (9,60000,2,0,3,1,0,"","今日の運勢は中吉！　旅行運がぐんぐんと上昇中♪　　　　　　　もしかしたら、あの「マホマホ王国」にだって行けるかも♪",0);
INSERT INTO `login_bonus_message_data` VALUES (10,60000,2,0,3,1,0,"","今日の運勢は中吉！　仕事運が急上昇中です！　　　　　　　　　きっと「煉獄に舞う一陣の疾風」の如き活躍ができますよ！",0);
INSERT INTO `login_bonus_message_data` VALUES (11,60000,2,0,3,1,0,"","今日の運勢は中吉！　チャンスを待つと良い結果に！　　　　　　ラッキーアイテムのプリンを食べて、運を呼び込みましょう！",0);
INSERT INTO `login_bonus_message_data` VALUES (12,60000,2,0,3,2,0,"","今日の運勢は中吉！　運気が着々と上昇中！　　　　　　　　　　精霊の加護を受けたかの如く、色々な事がうまくいきますよ♪",0);
INSERT INTO `login_bonus_message_data` VALUES (13,60000,2,0,4,1,0,"","今日の運勢は小吉！　早朝に幸運の兆しあり！　　　　　　　　　もしかしたら、優しいお姉ちゃんが起こしにきてくれますよ♪",0);
INSERT INTO `login_bonus_message_data` VALUES (14,60000,2,0,4,1,0,"","今日の運勢は小吉！　運気上昇中ですが、上がるまでが要注意！　ラッキーアニマルは熊！　本当の家族のように守ってくれるかも♪",0);
INSERT INTO `login_bonus_message_data` VALUES (15,60000,2,0,4,1,0,"","今日の運勢は小吉！　外に出てゆっくり過ごすと運気が上昇！　　ラッキースポットは牧場。面白い出会いがありそうです♪",0);
INSERT INTO `login_bonus_message_data` VALUES (16,60000,2,0,4,1,0,"","今日の運勢は小吉！　運気は高いけども、ハプニングには注意！　出かけた先で、「ふしんしゃ」扱いされてしまうかも……",0);
INSERT INTO `login_bonus_message_data` VALUES (17,60000,2,0,4,2,0,"","今日の運勢は小吉！　根を詰めずにリラックスすると運気向上！　ラッキーパーソンはアイドル。歌があなたを幸せにしてくれます♪",0);
INSERT INTO `login_bonus_message_data` VALUES (18,60000,3,0,0,0,190804,"カリン","おみくじの結果はどうでしたか？\n新たに始まる一日が、あなたに\nとって良い日になりますように\nまた明日も遊びに来て下さいね♪",2);
INSERT INTO `login_bonus_message_data` VALUES (19,60000,3,7,0,0,190804,"カリン","おみくじは楽しんで頂けましたか？\nあなたの新たなる年が\n素晴らしいものになるよう、\n心からお祈りいたします",3);
